CREATE TABLE clients (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE accounts (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id),
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    balance NUMERIC(19, 2) NOT NULL DEFAULT 0.0
);